src/Masthead/masthead.scss
stories/Masthead.stories.mdx

Fix padding left and right for tablet view and below
Fix dropdown arrow size

Masthead fixes

---

index.html
src/Button/sgds-button.ts
src/Input/index.ts
src/Input/sgds-input.scss
src/Input/sgds-input.ts
src/index.ts
src/utils/defaultvalue.ts
src/utils/form.ts
src/utils/watch.ts
stories/Button.stories.mdx
stories/Input.stories.mdx
test/button.element.test.ts
test/input.element.test.ts

**Input**
- add validation
- added form submit controller and watch decorator
- Input web component
- storybook documentation
**Button**
- added form submit controller and watch decorator
- storybook documentation

Input and button

---

src/components/Masthead/sgds-masthead.ts

- summary
- fluid prop description
- css properties

sgds-506-masthead

---

docs/Vue.md
stories/frameworks/Vue.stories.mdx

Add vue documentation for sgds web component 
tested with own vue app

docs(vue): add setup docs for vue'

---

src/components/Textarea/sgds-textarea.scss
src/components/Textarea/sgds-textarea.ts
src/main.ts
stories/templates/Textarea/additional.mdx
stories/templates/Textarea/basic.js
test/textarea.test.ts

**Validation**
make validation styles optional with hasFeedback
make invalid and valid internal states
**Storybook**
Added jsdocs
add validation story example
add defaultValue story example

Sgds 511 textarea

---

src/components/Footer/sgds-footer.ts
stories/templates/Footer/basic.js
test/footer.test.ts

- footer summary
- props description
- Hard code `report vulnarabilites` link. This should be govern by SGDS
- update type:string to props
-  remove quotation marks for href links

sgds-503-footer

---

docs/React.md
stories/frameworks/React.stories.mdx

1) Tested out with client side react 
2) Added react documentation

docs(*): react documentation

---

README.md

chore(*): update readme

---

index.html
src/components/Breadcrumb/sgds-breadcrumb-item.ts
src/components/Breadcrumb/sgds-breadcrumb.scss
src/components/Breadcrumb/sgds-breadcrumb.ts
stories/templates/Breadcrumb/basic.js
test/breadcrumb.test.ts

-[X] Small Refactoring changes :
1. Refactor the separator in favour of slots . Remove the css custom variable to change separator via css. This will allow more flexibility of what is the separator can be (in svgs, text, html elmeents) 
2. Remove autofocus features on input as sgds not supporting this feature 
-[X] JsDocs 
-[X] Storybook  props wiring
-[X] Update unit tests
- [] I have commented my code, particularly in hard-to-understand areas

Sgds 530 breadcrumb

---

src/components/Spinner/sgds-spinner.ts
stories/templates/Spinner/basic.js

Add JSDocs only as everything else is fine

Sgds 533 spinner

---

src/base/sgds-element.scss
src/components/Stepper/sgds-stepper.scss
src/components/Stepper/sgds-stepper.ts

Added 3 new custom variables for stepper
```
--sgds-stepper-theme-color: var(--sgds-primary);
--sgds-stepper-theme-hover-color: var(--sgds-primary-600);
--sgds-stepper-default-color: var(--sgds-gray-400);
```
```
```

Sgds 535 stepper color

---

docs/Stylings.md
src/base/sgds-element.scss
src/base/sgds-element.ts

Refactor and added all state colors custom variables for
`$primarys, $secondarys, $successs, $infos, $dangers, $warnings, $lights, $darks`
```
--sgds-{colors}-{weight}
```
```
```

style(colors): generating custom variable for all state colors

---

src/components/Drawer/sgds-drawer.scss

Fixed header padding
Fixed close-button alignment
```
```

Sgds 555 drawer

---

index.html
src/components.ts
src/components/Progress/index.ts
src/components/Progress/sgds-progress-bar.scss
src/components/Progress/sgds-progress-bar.ts
src/components/Progress/sgds-progress.scss
src/components/Progress/sgds-progress.ts
stories/templates/Progress/basic.js
test/progress.test.ts

feat(progress): add progress component

---

src/base/sgds-element.scss
src/components/Table/sgds-table.scss
src/components/Table/sgds-table.ts

Forward table custom variables to component level
```
:host{
//table
--table-bg: transparent;
--table-accent-bg: transparent;
--table-striped-color: var(--sgds-gray-600);
--table-striped-bg: rgba(0, 0, 0, 0.05);
--table-active-color: var(--sgds-gray-600);
--table-active-bg: rgba(0, 0, 0, 0.1);
--table-hover-color: var(--sgds-gray-600);
--table-hover-bg: rgba(0, 0, 0, 0.075);
.table{
--sgds-table-bg: var(--table-bg);
--sgds-table-accent-bg:  var(--table-accent-bg);
--sgds-table-striped-color:  var(--table-striped-color);
--sgds-table-striped-bg:  var(--table-striped-bg);
--sgds-table-active-color:  var(--table-active-color);
--sgds-table-active-bg:  var(--table-active-bg);
--sgds-table-hover-color:  var(--table-hover-color);
--sgds-table-hover-bg:  var(--table-hover-bg);
}
}
```
```
Please …
```

Table custom variable

---

src/components/Stepper/sgds-stepper.ts
test/stepper.test.ts

Changes are made to Stepper based on previous recommendations made for React stepper:
```
```

Implement a11y for Stepper

---

CHANGELOG.md
package-lock.json
package.json

Including dropdown-a11y changes

Merge in v1.0.0-rc.5 

---

stories/templates/Datepicker/basic.js

Fix storybook basic Datepicker example 
```
```
Tested on Dev branch

docs(datepicker): fix storybook example on datepicker

---

.storybook/manager.js
.storybook/preview-head.html
.storybook/sgdsTheme.js
docs/Introduction.md
package-lock.json
package.json

- Added notice banner for scheduled maintenance.
- Added SGDS theming 
```
```

Add notice banner

---

docs/INSTALLATION.md
docs/Next.md
docs/React.md
stories/frameworks/Next.stories.mdx

Docs update for scoped elements installatino usage and create new section for nextjs
https://github.com/open-wc/open-wc/pull/2733

Nextjs and installation docs update

---

docs/INSTALLATION.md
docs/ScopedElements.md
index.html
stories/getting-started/Usage/ScopedElements.stories.mdx

https://github.com/open-wc/open-wc/pull/2733
https://dev.webcomponent.designsystem.tech.gov.sg/?path=/docs/getting-started-installation--page
Updating docs based on scoped element changes
```
```

docs(polyfill): update polyfill instructions

---

index.html
src/components/Pagination/sgds-pagination.ts
stories/templates/Pagination/additional.mdx
stories/templates/Pagination/basic.js
test/pagination.test.ts

showLastPage and showFirstPage props 
```
```

feat(pagination): showFirstPage showLastPage [skip-cd]

---

CHANGELOG.md
cypress/apps/react-app/package-lock.json
index.html
package-lock.json
package.json
src/components/Accordion/sgds-accordion.ts
src/components/Datepicker/sgds-datepicker.ts
src/components/Mainnav/sgds-mainnav.ts
src/components/Sidenav/sgds-sidenav-item.ts
src/components/Sidenav/sgds-sidenav-link.ts
src/components/Sidenav/sgds-sidenav.ts
test/mainnav.test.ts
test/sidenav.test.ts
test/tooltip.element.test.ts

1) Refactor components using Bootstrap Collapse dependency to use own animation logic 
2) Remove usage of Bootstrap Collapse as it conflicts with bootstrap.bundle.js cdn. 
This will resolve the [issue](https://github.com/GovTechSG/sgds/issues/477) on our portal 
and some of users who have the similar case where they are using both bootstrap.bundle.js and our web component library
```
```
Refactor with no breaking changes and no need for documentation update

Refactor bootstrap collapse deps [skip-cd]

---

mocks/stepper.ts

fix(stepper): stepper example not showing [skip-cd]

---

.storybook/manager.js
.storybook/sgdsTheme.js
stories/templates/ComboBox/additional.mdx

Fix combo box with custom filter example
```
```

fix(combobox): custom filter example not showing [skip-cd]

---

README.md
coverage/lcov-report/base.css
docs/Stylings.md
index.html
package-lock.json
package.json
src/components/Masthead/sgds-masthead.scss
src/utils/components.style.scss

chore(*): remove Helvetica font

---

CONTRIBUTING.md

Update git command from typo
```
```

fix(*): fix git command instead of npm push

---

stories/templates/Breadcrumb/basic.js

Add a default value for `href` prop for home
```
```

chore(breadcrumb): add a default href for home

---

.storybook/global.css
.storybook/preview.ts
docs/FAQ.md
src/components/Accordion/sgds-accordion-item.scss
stories/troubleshooting.stories.mdx

Troubleshooting page

---

docs/Next.md

Update Next documentations to directy re-export the components, as additional steps may be needed to forward the props for use. 
Also include a small example to use the components.
```
```
N.A., documentation changes

docs: update docs for nextjs client components

---

src/components/Card/sgds-card.ts

docs(card): add storybook description for icon slot

---

stories/templates/Icon/basic.js

chore(icon): update import statement for storybook

---

src/components/DescriptionList/description-list.css
src/components/DescriptionList/sgds-description-list-group.ts

style(description list): update bordered descrption list styling

---

mocks/pagination.ts
src/components/Table/sgds-table.ts

chore(table): fixing test errors

---

docs/Grid.md
docs/INSTALLATION.md
src/css/grid.css
src/themes/root.css
stories/style/GridSystem.mdx
stories/style/grid.stories.js

Update new grid breakpoints and added utilities to center grid item
```
```

feat(grid): add new breakpoint and utilities to center grid items

---

src/components/Accordion/sgds-accordion-item.ts

Fix the SSR flickering issue of the accordion during page load.
```
```

fix(accordion): fix flickering issue of accordion body on page load with SSR

---

stories/templates/Input/additional.mdx
stories/templates/Input/additional.stories.js
stories/templates/Input/basic.js

Leading icon in input is available , so updating the documentation 
```
```

docs(input): add Leading Icon example in storybook

---

cypress/apps/nuxt-app/package-lock.json
src/base/button.css
src/components/Subnav/sgds-subnav.ts
src/components/Subnav/subnav-item.css
src/components/Subnav/subnav.css

remove the usage of window object in default state as it causes error in SSR
```
```

fix(subnav): remove the usage of window object in default state

---

playground/Toast.html
src/components/Toast/toast.css

Add a missing gap between header and body 
```
```

fix(Toast): missing gap between title and body

---

playground/Dropdown.html
src/components/ComboBox/combo-box-item.css
src/components/Dropdown/dropdown-item.css
src/components/Select/select-item.css

Modify menu item to remove nowrap to allow long sentences to go next line 
```
```

style(menuItem): dropdown-item, select-item, combo-box-item remove nowrap

---

src/components/Mainnav/mainnav.css

fix styling break on mainnav mobile view
```
```

style(main nav): remove position relative on mainnav for styling break

---

tsconfig.json

fix(*): restores types definition in the library

---

stories/templates/Button/additional.mdx

Fix the button variant typo in storybook
```
```

docs(storybook): fix button variant typo

---

src/base/card.css
src/components/ThumbnailCard/sgds-thumbnail-card.ts
src/components/ThumbnailCard/thumbnail-card.css
test/thumbnail-card.test.ts

Remove rounded corner from thumbnail to support any image ratio
```
```

style(thumbnail card): remove rounded corner from thumbnail to support any image ratio

---

src/components/Subnav/subnav.css

Reduce z-index so that it won't crash with mainnav dropdown
```
```

style(subnav): reduce z-index to avoid clashes with mainnav

---

src/base/sgds-element.css
src/styles/reboot.css

Update the css selector to see if it works on ios 17.
```
```

style(*): update global css selector for box-sizing

---

docs/INSTALLATION.md
package-lock.json
package.json

chore(*): upgrade reactdom and react dep to 19 using overrides
