GovTechSG/sgds-web-component

- src/components/Sidenav/sgds-sidenav-item.scss
- src/components/Sidenav/sgds-sidenav-item.ts
- src/components/Sidenav/sgds-sidenav-link.scss
- src/components/Sidenav/sgds-sidenav-link.ts
- src/components/Sidenav/sgds-sidenav.scss
- src/components/Sidenav/sgds-sidenav.ts
- stories/templates/Sidenav/basic.js
- test/sidenav.test.ts
- added summary description
- move `--sidenav-theme-color`to `sidenav`
- rename and add css properties
- added css properties descriptions
- rename and add css properties
- added css properties descriptions
- added method and props description
- added missing slot `a.sidenav-btn > slot[name="icon"]`
- added missing slot `a.sidenav-btn > slot[name="icon"]`
- fix storybook notation
> sgds-504-sidenav

- src/components/ActionCard/sgds-action-card.scss
- src/components/ActionCard/sgds-action-card.ts
- src/components/Checkbox/sgds-checkbox.ts
- src/components/Radio/sgds-radio-group.ts
- src/components/Radio/sgds-radio.ts
- stories/templates/ActionCard/additional.mdx
- stories/templates/ActionCard/basic.js
- stories/templates/Radio/basic.js
- test/action-card.test.ts
Feature added
1) Incorporate form props and behaviours to action card so that it acts like a form component 
2) Set the behaviours for action card when it is a radio. Let radio card be wrapped in radio-group to manage the radio behaviours in a form context
3) Handle the active stylings when radio cards/ checkbox cards are clicked 
4) quantity toggle card variant is not supported yet so I removed variant prop 
Test
Check that test cases have passed and added new test case for the form behaviours
Storybook 
Update with an example of radio cards as a form 
JSdocs added
> Sgds 512 action card

- index.html
- src/components/Mainnav/sgds-mainnav-dropdown.ts
- stories/templates/Mainnav/basic.js
- test/mainnav.test.ts
Fix sgds-mainnav-dropdown alignment issue 
- Mainnav dropdown was not aligning directly on the bottom of the link
- 
```
```
- 
> fix(mainnav): align dropdown menu right below li

- src/base/sgds-element.scss
- src/components/Badge/sgds-badge.ts
Refactor variant css tokens
Adding `$theme-colors-rgb` color mixin loop 
Generating all $theme-colors in `variables.scss`.
Both badge and spinner components are working as intended.
```
```
> [CSS] Refactor variant css tokens

- src/components/Sidenav/sgds-sidenav.scss
there is extra padding-left on sidenav 
Remove ul's native style padding-left 
```
```
> fix(sidenav): remove padding left

- src/components/Alert/sgds-alert.scss
vertical align stylings coming from bootstrap reboot scss causing svg icon to be out of line. 
```
```
> fix(alert): remove default svg vertical align stylings for alert

- src/base/dropdown-element.ts
- src/components/ComboBox/sgds-combo-box.ts
- src/components/Datepicker/sgds-datepicker.ts
- src/components/Dropdown/sgds-dropdown.ts
- test/dropdown.test.ts
**sgds-dropdown**
- Add button role, aria-expanded, aria-haspopup
**sgds-combo-box**
- Add combobox role, aria-expanded (will not be read by screen-reader because button role is not indicated), aria-autocomplete, aria-controls
**sgds-datepicker**
- add combobox role, aria-haspopup, aria-controls
- Change dropdown-menu role to 'dialog'
**Current issues**
- Dropdown components that use input as toggler (e.g. combobox, datepicker) are not screen-reader accessible (user cannot click to open dropdown menu)
- When dropdown menu opens, screen-reader does not shift focus to the dropdown menu (even though I implemented aria-controls attribute, might be a limitation of web components (?) ). I tried doing it programatically by calling dropdownMenu.focus() when dropdown menu opens. But not quite a …
> WIP: Implement a11y for Dropdown

- vite.config.js
Temporarily ignoring the vite inline?css warning in dev mode, until i got the bandwidth to fix it. 
Tempora
```
```
> build(vite): temporarily ignoring inline-css warning from vite dev

- cypress/apps/angular-app/package-lock.json
- cypress/apps/react-app/package-lock.json
- cypress/apps/vue-app/package-lock.json
- index.html
- package-lock.json
- package.json
- rollup.config.mjs
latest version uses lit over lit-element by default
Due to rollup-plugin-postcss-lit, using lit-element package by default. 
Update to latest version resolves the issue as the package is using lit now. 
#170
```
```
> Fix lit-element deprecated console warning [skip-cd]

- index.html
- src/components/Accordion/sgds-accordion.ts
- src/components/Datepicker/datepicker-calendar.scss
- src/components/Datepicker/datepicker-calendar.ts
- src/components/Datepicker/datepicker-header.scss
- src/components/Datepicker/datepicker-header.ts
- src/components/Datepicker/datepicker-input.ts
- src/components/Datepicker/sgds-datepicker.ts
- src/components/Datepicker/types.ts
- src/components/Input/sgds-input.ts
- src/components/Sidenav/sgds-sidenav.ts
- test/datepicker.test.ts
- test/input.element.test.ts
A11y attributes added
1) aria-labels on dates, months to allow screen reader to read out the full date / month 
2) aria-labels on dialog, arrow and header buttons, current month / year buttons
3) aria-live= polite on datepicker header for screen reader to annouce the header 
4) aria-current on today's date
5) aria-invalid and aria-describedby for invalid input state and corresponding feedback 
Styling changes
1) add hover styles to arrow and header buttons 
2) Shift focus back to input so that screen reader can read the selected date 
```
```
> A11y/datepicker patches [skip-cd]

- .storybook/preview-head.html
- index.html
- src/components/QuantityToggle/sgds-quantity-toggle.ts
- stories/templates/QuantityToggle/basic.js
- test/quantitytoggle.test.ts
To fix quantity toggle button and update the test case.
1. prevent the users from entering the negative("-") value or any other alphabets
2. reset the value to 0 when the value is blank (deletion)
3. disable button when number reach 0 / minimum / maximum value
```
```
> Fix quantity toggle [skip-cd]

- src/components/Modal/sgds-modal.ts
- stories/templates/Modal/basic.js
- test/modal.test.ts
Add prop `noCloseButton` to allow removal of close button. 
```
```
> feat(modal): add noCloseButton prop

- src/components/Pagination/sgds-pagination.ts
- test/pagination.test.ts
Fix duplicate first page button when `showFirstPage` is set and `limit` equals to page length.
```
```
> fix(pagination): duplicate first page button

- src/components/Switch/sgds-switch.ts
- test/switch.test.ts
There is a gap for empty label on the right when the label is displayed on the left. Refactored the component to hide the empty label.
```
```
> fix(switch): hide label to avoid flex gap issue

- src/components/Dropdown/dropdown-item.css
- src/components/Dropdown/sgds-dropdown-item.ts
- test/dropdown.test.ts
Bug found that when clicking outside of the label of Dropdown Item but still within the area of DropdownItem, the navigation doesnt work 
This is because the navigation is tied to "anchor" tag, which area does not span the entire dropdown item. I tried to use width 100%, but the height will still be a problem due to the padding in DropdownItem 
hence i applied a javascript solution to listen for click events happening in DropdownItem and trigger a click on the anchor if that happens 
```
```
> fix(DropdownItem): click area bug

- playground/IconList.html
- src/components/IconList/icon-list.css
#309 
Fix the alignment of the icon list and text to align at top instead of center
```
```
> style(icon list): align icon and text at top instead of center

- package-lock.json
- package.json
- src/utils/validatorMixin.ts
In react development mode, strict mode is enabled and is encouraged for users to run strict mode. The strict mode stress tests the component and calls connectedCallback more than once. Hence, we should make sure that the attachInternals() is idempotent and should not run more than once even if connectedCallback is called multiple times. 
In production mode, react runs connectedCallback once. 
Tested in v3.3.2-rc.0 with a nextjs app
#368
```
```
> fix(validation): make ElementInternals instantiation idempotent

- playground/Pagination.html
- src/components/Pagination/sgds-pagination.ts
- test/pagination.test.ts
Disable next button when pages length <= 1
#319
```
```
> fix(Pagination): next button to disable  where pages length is less than 2

- src/components/Button/button.css
- src/components/Button/sgds-button.ts
- test/button.element.test.ts
Remove flex gap when no icon is present, since external link icons now use margin for spacing and wrapping.
```
```
> style(button): remove gap when there is no icon

- rollup.config.mjs
Should include full name or regex that matches "floating-ui/dom" else this package won't be properly externalized from the final library build resulting in this error
pushed this build to rc and tested  v3.5.1-rc.2  on local angular app. Error is gone
```
```
> build(*): use full name of floating ui to externalise it
